# Travis-CI Build for Joy

language: c

compiler: gcc

before_install:
    - sudo apt-get -qq update

install:
    - sudo apt-get install -y build-essential libssl-dev libpcap-dev libcurl4-openssl-dev cppcheck

script:
    - ./configure --enable-gzip
    - make clean
    - make
    - bin/unit_test
    - test/run_tests.py
    - ./.cppcheck.sh
